### PR TITLE
Fix Worker

### PR DESCRIPTION
**Pull request by seanpdoyle**
* Use `NodeResque.multiWorker` instead of single worker.
* Chain `callback` after linter finishes
* Fix `lib/test-queue` requires.
* Fix integration test assertions

### CODE REVIEW

**Comment by teoljungberg** [comment]
This is the same PR as done in [eslint] and [jscs]

[eslint]: https://github.com/thoughtbot/hound-eslint/pull/3
[jscs]: https://github.com/thoughtbot/hound-jscs/pull/4

**Comment by teoljungberg** [comment]
Since we tested the others, should we test this one aswell?

Besides that question, this looks good to me

**Comment by seanpdoyle** [comment]
@teoljungberg given the failures we saw before this fix, I say yes (at least once).

I'll be making a similar change on https://github.com/thoughtbot/hound-mdast

**Comment by teoljungberg** [comment]
I'll go ahead and merge this

**Pull request merged**
